### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by ZenthShadowflame** [Bumblecat/Foodsicles#2]
I had this mod as part of my modpack because I enjoy using the Foodsicle in my personal game. However when I tried to load it the console log stated that it was crashing because of this mod. Talking to someone who knew more about mods they said that it was because it was trying to load client side only content onto the server and that caused it to crash.

Below is a record of the console log that I gave them to check.
https://paste.shockbyte.com/iyoziwogifibucerizoy

**Comment by Baijson** [comment]
Hi! 

I think this issue has been resolved in the 1.0.8 version, but can't test it thoroughly as I don't have a remote server to test it on. (testing it on a localhost server did not reproduce this crash)

If you could and want to confirm that the issue has been resolved, that would be great!
Thank you.
